services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Helhum\TYPO3\Crontab\Crontab:
        class: 'Helhum\TYPO3\Crontab\Crontab'
        arguments: []

    Helhum\TYPO3\Crontab\ViewHelpers\:
        resource: '../Classes/ViewHelpers/*'

    Helhum\TYPO3\Crontab\Controller\:
        resource: '../Classes/Controller/*'

    Helhum\TYPO3\Crontab\Command\:
        resource: '../Classes/Command/*'

    Helhum\TYPO3\Crontab\Repository\:
        resource: '../Classes/Repository/*'

    Helhum\TYPO3\Crontab\Command\CrontabCommand:
        tags:
            -   name: 'console.command'
                command: 'crontab:run'
                description: 'Start Crontab from the command line'
                schedulable: false

    Helhum\TYPO3\Crontab\Command\CrontabProcessCommand:
        tags:
            -   name: 'console.command'
                command: 'crontab:execute'
                description: 'Directly runs the Crontab Task with given identifier'
                schedulable: false

    Helhum\TYPO3\Crontab\Command\CrontabScheduleCommand:
        tags:
            -   name: 'console.command'
                command: 'crontab:schedule'
                description: 'Adds/removes given tasks to/from schedule'
                schedulable: false

    Helhum\TYPO3\Crontab\Command\CrontabImportSchedulerTasksCommand:
        tags:
            -   name: 'console.command'
                command: 'crontab:import-scheduler-tasks'
                description: 'Import Scheduler Tasks'
                schedulable: false

    Helhum\TYPO3\Crontab\EventListener\BeforeModuleCreationEventListener:
        tags:
            -
                name: 'event.listener'
                identifier: 'helhum/typo3-crontab/before-module-creation-event-listener'
